### PR TITLE
Fix WPForms form creation

### PR DESCRIPTION
**Pull request by dreamwhisper**
Fixes the OCTS _Contact Us_  form creation.

### How to test

1. Using this branch on a fresh site, go to Genesis > Child Theme Setup and run your choice of OCTS.
2. Make sure that:
    - [ ] Form is created under WPForms > All Forms
    - [ ] Form contains fields
    - [ ] Form displays fields on the `contact-us` page.

### Documentation
No documentation required.

### Suggested changelog entry

- Fixed: One-click theme setup WPForms contact form creation.

### CODE REVIEW

**Review by kienstra — APPROVED** [review]
Hi @dreamwhisper,
This looks good!

**Comment by dreamwhisper** [comment]
Thanks @kienstra!

**Comment by kienstra** [comment]
Of course!

**Comment by kienstra** [comment]
The 'Contact Us' page looks good:

Screen Shot 2022-11-03 at 1 20 24 PM

**Pull request merged**
