### PR TITLE
GF-1740 deploy to StudioPress

### PR DESCRIPTION
**Pull request by BMO-tech**
**Summary of change:**
This PR adds two new CircleCI jobs to upload the generated artifact to StudioPress' staging site, then production site.

**See:** GF-1740 Internal Jira task

### CODE REVIEW

**Comment by nickcernis** [comment]
@BMO-tech Approved! Thanks again for all the work that went into this.

Should we document the CircleCI vars somewhere? (Perhaps the [wiki](https://github.com/studiopress/genesis-sample/wiki), or a Google doc in the team drive?)

I'm also not 100% certain that theme files are currently served from `/wp-content/uploads/studiopress-downloads/` (because I don't see recent theme uploads there on the production server), but that's something we can easily adjust if needed after using this.

**Comment by BMO-tech** [comment]
Before I merge this, can we get confirmation as to where theme files are uploaded? It's easier to update that path now. :)

**Comment by mattlawck** [comment]
@BMO-tech Dropping pwd(s) direct!

**Comment by BMO-tech** [comment]
Upload paths have been updated

**Comment by nickcernis** [comment]
Thanks, @BMO-tech and @mattlawck!

**Pull request merged**
